import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (name) => fs.readFileSync(path.join(root, name), "utf8");

test("Edge extension schedules one sequential daily collector run", () => {
  const manifest = JSON.parse(read("edge-automation/extension/manifest.json"));
  const background = read("edge-automation/extension/background.js");
  assert.equal(manifest.manifest_version, 3);
  assert.ok(manifest.content_scripts.some((entry) => entry.world === "MAIN" && entry.js.includes("auto-bridge.js")));
  assert.match(background, /const SOURCE_ORDER = \{ naver: 1, daangn: 2, gongsil: 3 \}/);
  assert.match(background, /periodInMinutes: 24 \* 60/);
  assert.match(background, /schedule: "11:00"/);
  assert.match(background, /LAST_SCHEDULE_KEY/);
  assert.match(background, /scheduleIsDue/);
  assert.match(background, /RUN_LOCK_KEY/);
  assert.match(background, /RUN_STATE_KEY/);
  assert.match(background, /RUN_REPORT_KEY/);
  assert.match(background, /if \(lock && \(!state \|\| !state\.active\)\)/);
  assert.match(background, /validateTarget\(target\)/);
  assert.match(background, /const result = await runAll\(reason\)/);
  assert.match(background, /LAST_SCHEDULE_KEY\]: localDateKey\(\)/);
  assert.match(background, /runScheduled\("browser-startup"\)/);
  assert.doesNotMatch(background, /chrome\.scripting\.executeScript/);
  assert.match(background, /async function launchCurrentTarget\(state, reuseTabId = null\)/);
  assert.match(background, /async function finishCurrentTarget\(result, senderTabId\)/);
  assert.match(background, /await sendRunMessage\(tab\.id, target, targetRunId, state\.runId\)/);
  assert.match(background, /JS_AUTO_TARGET_FINISHED/);
  assert.match(background, /JS_AUTO_RUN_REQUEST/);
  assert.match(background, /chrome\.tabs\.onRemoved/);
  assert.match(background, /chrome\.tabs\.create\(\{ url: target\.url, active: false \}\)/);
  assert.doesNotMatch(background, /chrome\.windows\.update\(tab\.windowId, \{ state: "minimized" \}\)/);
  assert.match(background, /async function restartPersistedRun\(state, reason\)/);
  assert.match(background, /async function resumeOrExtendActiveRun\(state, targets, reason\)/);
  assert.match(background, /누락 대상 .*개를 추가/);
  assert.match(background, /chrome\.tabs\.get\(state\.currentTabId\)/);
  assert.match(background, /retryQueue/);
  assert.match(background, /RECOVERY_ALARM_NAME/);
  assert.match(background, /WATCHDOG_ALARM_NAME/);
  assert.match(background, /async function ensureWatchdogAlarm\(\)/);
  assert.match(background, /chrome\.alarms\.get\(WATCHDOG_ALARM_NAME\)/);
  assert.match(background, /async function runAll\(reason = "manual"\) \{\s*await ensureWatchdogAlarm\(\)/);
  assert.match(background, /async function resumeOrExtendActiveRun\(state, targets, reason\) \{\s*await ensureWatchdogAlarm\(\)/);
  assert.match(background, /async function updateTargetHeartbeat\(message, senderTabId\)[\s\S]{0,700}await ensureWatchdogAlarm\(\)/);
  assert.match(background, /MAX_IMMEDIATE_ATTEMPTS = 4/);
  assert.match(background, /MAX_DEFERRED_RETRY_CYCLES = 8/);
  assert.match(background, /MAX_RUN_AGE_MS/);
  assert.match(background, /COLLECTOR_START_TIMEOUT_MS = 2 \* 60 \* 1000/);
  assert.match(background, /COLLECTION_STALL_TIMEOUT_MS = 20 \* 60 \* 1000/);
  assert.match(background, /COLLECTION_HEARTBEAT_TIMEOUT_MS = 8 \* 60 \* 1000/);
  assert.match(background, /MAX_TARGET_RUNTIME_MS = 90 \* 60 \* 1000/);
  assert.match(background, /targetRuntimeExceeded/);
  assert.match(background, /한 지역 수집이 90분/);
  assert.match(background, /주소·층 오류/);
  assert.match(background, /state\.summary\.failed = Number\(state\.summary\.failed \|\| 0\) \+ 1/);
  assert.match(background, /state\.summary\.retryErrors/);
  assert.match(background, /stalledLoading/);
  assert.match(background, /stalledStart/);
  assert.match(background, /stalledCollection/);
  assert.match(background, /disconnectedCollection/);
  assert.doesNotMatch(background, /onInstalled[\s\S]{0,400}remove\(\[RUN_STATE_KEY, RUN_LOCK_KEY\]\)/);
});

test("automatic targets and schedules stay in the dedicated Edge profile", () => {
  const background = read("edge-automation/extension/background.js");
  const content = read("edge-automation/extension/content.js");
  assert.match(background, /chrome\.storage\.local/);
  assert.doesNotMatch(background, /COLLECTOR_ACCESS_KEY|collectorKey|accessKey/);
  assert.match(content, /JS_COLLECTOR_AUTOMATION_RESULT/);
  assert.match(content, /async function signalScheduledRun\(autorun, forceRun\)/);
  assert.match(content, /attempt < 12/);
  assert.match(content, /JS_AUTO_START_MAIN/);
  assert.match(content, /JS_AUTO_TARGET_FINISHED/);
  assert.match(content, /async function reportTargetFinished\(message\)/);
  assert.match(content, /sendResponse\(\{ ok: true, started: true \}\)/);
  assert.match(content, /RESULT_TIMEOUT_MS/);
  assert.match(content, /RESULT_TIMEOUT_MS = 90 \* 60 \* 1000/);
  assert.match(content, /START_ACK_TIMEOUT_MS = 35 \* 1000/);
  assert.match(content, /JS_COLLECTOR_AUTOMATION_STARTED/);
  assert.match(content, /\[data-metric\]/);
  assert.match(content, /JS_AUTO_TARGET_HEARTBEAT/);
  assert.match(content, /function stableProgressText\(value\)/);
  assert.match(content, /stableProgressText\(detail\)/);
  assert.match(content, /JS_AUTO_COLLECTOR_PAGE_LOADED/);
  const bridge = read("edge-automation/extension/auto-bridge.js");
  assert.match(bridge, /async function waitForRuntime/);
  assert.match(bridge, /JS_COLLECTOR_AUTOMATION_STARTED/);
  assert.match(bridge, /activeRuns/);
});

test("all three collectors expose registration and unattended execution", () => {
  const naver = read("js/naver-collector.js");
  const daangn = read("js/daangn-collector.js");
  const gongsil = read("js/gongsil-collector.js");
  for (const source of [naver, daangn, gongsil]) {
    assert.match(source, /data-action="auto-register"/);
    assert.match(source, /runAutomatic: runAutomatic/);
    assert.match(source, /JS_COLLECTOR_REGISTER_TARGET/);
  }
  assert.match(gongsil, /clickScreenLargestCluster/);
  assert.match(gongsil, /현재 화면 전체클러스터 자동수집 등록/);
  assert.match(naver, /data-role="auto-district"/);
  assert.match(naver, /function selectAutomaticDistrict\(\)/);
  assert.match(naver, /AUTO_DISTRICT_PROGRESS_KEY/);
  assert.match(naver, /async function collectFinAutomaticDistrict\(district\)/);
  assert.match(naver, /NAVER_LIST_REQUEST_TIMEOUT_MS = 60000/);
  assert.match(naver, /new AbortController\(\)/);
  assert.match(naver, /네이버 목록 응답이 60초 안에 없어 다시 시도합니다/);
  assert.match(naver, /saveAutoDistrictProgress\(progress\)/);
  assert.match(naver, /clearAutoDistrictProgress\(district\.cortarNo\)/);
  assert.match(daangn, /state\.job\.completionIssues/);
  assert.match(daangn, /hardFailed = Math\.max\(0, Number\(state\.job\.failed/);
  assert.match(daangn, /partial: partial/);
  assert.match(daangn, /scheduleManualRecovery\(message\)/);
  assert.match(daangn, /manualRecoveryAttempts >= 5/);
  assert.match(daangn, /function getScopedClientId\(url\)/);
  assert.match(daangn, /jobRequestGeneration/);
  assert.match(daangn, /\{jobUrl: state\.job\.url\}/);
  assert.match(daangn, /SQLITE_TOOBIG\|string or blob too big/);
  assert.match(daangn, /new AbortController\(\)/);
  assert.match(daangn, /controller\.abort\(\)/);
  assert.match(daangn, /await refreshJobStatus\(\);[\s\S]*?await startOrResume\(\)/);
  assert.match(daangn, /state\.job\.status === "running"[\s\S]*?scheduleNextChunk\(\)/);
  assert.match(naver, /지도 클러스터 인식과 관계없이/);
  const naverAutomatic = naver.slice(naver.indexOf("async function runAutomatic"), naver.indexOf("function requestSafeStop"));
  assert.doesNotMatch(naverAutomatic, /discoverFinContext\(\)/);
});

test("provider omissions complete a target with a warning instead of restarting it from zero", () => {
  const background = read("edge-automation/extension/background.js");
  assert.match(background, /function completedTargetWithWarnings\(result\)/);
  assert.match(background, /cleanSource\(payload\.source\) !== "naver"/);
  assert.match(background, /session\.completeRequested === true/);
  assert.match(background, /const successful = result\.ok === true && !payloadPartial/);
  assert.match(background, /successful \|\| warningCompletion/);
  assert.match(background, /state\.summary\.partial/);
  assert.match(background, /전체 목록 확인 완료/);
});

test("Windows installer creates a daily recoverable scheduled task", () => {
  const install = read("tools/install-edge-auto-collector.ps1");
  const uninstall = read("tools/uninstall-edge-auto-collector.ps1");
  const launch = read("tools/run-edge-auto-collector.ps1");
  assert.match(install, /New-ScheduledTaskTrigger -Daily/);
  assert.match(install, /\[string\]\$Schedule = '11:00'/);
  assert.doesNotMatch(install, /New-TimeSpan -Minutes 30/);
  assert.match(install, /-StartWhenAvailable/);
  assert.match(install, /-WakeToRun/);
  assert.match(uninstall, /Unregister-ScheduledTask/);
  assert.match(launch, /--user-data-dir=/);
  assert.match(launch, /--load-extension=/);
  assert.match(launch, /--new-tab/);
  assert.match(launch, /chrome-extension:\/\/\$extensionId\/autorun\.html/);
  assert.match(launch, /chrome-extension:\/\/\$extensionId\/options\.html/);
  assert.match(launch, /\/json\/list/);
  assert.match(launch, /Reuse an existing status tab/);
  assert.match(launch, /jsAutoCollectorConfigV1/);
  assert.match(launch, /remote-debugging-port=9223/);
  assert.match(launch, /Invoke-RestMethod -Method Put/);
  assert.match(launch, /second idempotent trigger/);
  assert.match(launch, /\[switch\]\$Force/);
  assert.match(launch, /JSMapWindow/);
  assert.match(launch, /if \(-not \$Setup\)/);
  assert.match(launch, /Stop-Process -Id \$_.ProcessId -Force/);
  assert.match(launch, /\$stillRunning/);
  assert.match(install, /installedCollectors/);
  assert.match(install, /gongsil-collector\.js/);
  assert.match(install, /Get-CimInstance Win32_Process/);
  assert.match(install, /Stop-Process -Id \$_.ProcessId/);
  assert.match(read("edge-automation/extension/autorun.js"), /JS_AUTO_RUN_REQUEST/);
  assert.match(read("edge-automation/extension/autorun.js"), /chrome\.runtime\.reload\(\)/);
});

test("automatic collector settings stay compact with long target URLs", () => {
  const options = read("edge-automation/extension/options.js");
  const styles = read("edge-automation/extension/options.css");
  assert.match(options, /function renderTargets\(targets\)/);
  assert.match(options, /function targetSummary\(target\)/);
  assert.match(options, /SOURCE_ORDER/);
  assert.match(styles, /grid-template-columns:auto minmax\(0,1fr\) auto/);
  assert.match(styles, /text-overflow:ellipsis/);
  assert.match(styles, /\.log-list\{max-height:430px;overflow-y:auto/);
  assert.match(options, /chrome\.runtime\.getManifest\(\)\.version/);
  assert.match(read("edge-automation/extension/options.html"), /id="autoVersion"/);
  assert.match(read("edge-automation/extension/options.html"), /id="runSummary"/);
  assert.match(options, /function renderRunSummary\(\)/);
  assert.match(options, /전체 실행 상태 확인 중/);
  assert.match(options, /response\.message/);
  assert.match(options, /function currentRunStatus\(response\)/);
  assert.match(options, /수집 실행 중/);
  assert.match(options, /부분완료/);
  assert.match(options, /10개 구/);
  assert.match(options, /jsAutoCollectorRunReportV1/);
});

test("automatic collection keeps one visible per-district report", () => {
  const background = read("edge-automation/extension/background.js");
  const options = read("edge-automation/extension/options.js");
  assert.match(background, /async function updateRunReport\(state, target, status/);
  assert.match(background, /status: "pending"/);
  assert.match(background, /"running"/);
  assert.match(background, /partial \? "partial" : "completed"/);
  assert.match(background, /canRetry \? "retry_wait" : "failed"/);
  assert.match(options, /STATUS_TEXT/);
  assert.match(options, /진행 중/);
  assert.match(options, /실패/);
});

test("automatic collector settings can move safely to another PC", () => {
  const background = read("edge-automation/extension/background.js");
  const options = read("edge-automation/extension/options.js");
  const page = read("edge-automation/extension/options.html");
  assert.match(background, /function normalizePortableConfig\(value\)/);
  assert.match(background, /JS_AUTO_IMPORT_CONFIG/);
  assert.match(background, /validateTarget\(target\)/);
  assert.match(options, /js-map-auto-collector/);
  assert.match(options, /function portableTarget\(target\)/);
  assert.match(options, /설정 파일 저장 완료/);
  assert.match(options, /개 대상 복원 완료/);
  assert.match(page, /id="exportConfig"/);
  assert.match(page, /id="importConfig"/);
  assert.doesNotMatch(options, /COLLECTOR_ACCESS_KEY|collectorKey|accessKey|password/);
});
