const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const api = fs.readFileSync(path.join(root, "cloudflare", "src", "elevator-capacity-api.js"), "utf8");
const buildingApi = fs.readFileSync(path.join(root, "cloudflare", "src", "building-register-api.js"), "utf8");
const building = fs.readFileSync(path.join(root, "js", "building-register-v6.js"), "utf8");
const d1 = fs.readFileSync(path.join(root, "cloudflare", "src", "d1-api.js"), "utf8");
const map = fs.readFileSync(path.join(root, "js", "map.js"), "utf8");
const script = fs.readFileSync(path.join(root, "js", "script.js"), "utf8");
const worker = fs.readFileSync(path.join(root, "cloudflare", "src", "worker.js"), "utf8");
const enrichment = fs.readFileSync(path.join(root, "cloudflare", "src", "elevator-enrichment.js"), "utf8");

assert.match(api, /getOperationInfoListV1/);
assert.match(api, /openapigw\.elevator\.go\.kr/);
assert.match(api, /getBuldElvtrList/);
assert.match(api, /buld_address/);
assert.match(api, /ratedCap/);
assert.match(api, /parcelAddressKey\(candidate\) === targetKey/);
assert.match(api, /roadAddressKey\(candidate\) === targetRoadKey/);
assert.match(api, /SERVICE_PAUSE_KEY/);
assert.match(api, /elevatorAddressVariants/);
assert.match(api, /enrichElevatorDetails/);
assert.match(api, /districtElevators/);
assert.match(api, /api-cache\/elevator-district-v\$\{DISTRICT_INDEX_VERSION\}/);
assert.match(api, /normalizeDataGoKrServiceKey/);
assert.match(api, /env\.ELEVATOR_OPERATION_SERVICE_KEY/);
assert.doesNotMatch(api, /env\.DATA_GO_KR_SERVICE_KEY/);
assert.match(api, /decodeURIComponent\(key\)/);
assert.match(api, /accessFailure \? "\+10 minutes" : "\+1 day"/);
assert.match(buildingApi, /getElevatorCapacityForListing/);
assert.match(buildingApi, /normalizeBuildingRegisterServiceKey/);
assert.match(buildingApi, /normalizeBuildingRegisterServiceKey\(env\.DATA_GO_KR_SERVICE_KEY\)/);
assert.match(buildingApi, /building_elevator_capacity=CASE WHEN \?1>0 THEN \?4 ELSE 0 END/);
assert.match(buildingApi, /elevator_registry_count=\?1/);
assert.match(buildingApi, /building_register_elevators=\?2/);
assert.match(buildingApi, /cachedBuildingLocation/);
assert.match(buildingApi, /roadAddress/);
assert.match(d1, /building_elevator_capacity/);
assert.match(map, /buildingElevatorCapacity/);
assert.doesNotMatch(building, /action=elevatorCapacity/);
assert.match(building, /BUILDING_CLIENT_VERSION_V811 = "8\.2\.9"/);
assert.match(script, /function buildListElevatorIconV843\(item\)/);
assert.match(script, /class="item-elevator-v650"/);
assert.doesNotMatch(script, /item-elevator-capacity-v820/);
assert.doesNotMatch(building, /item-elevator-capacity-v820/);
assert.match(building, /elevatorDescription[\s\S]*최대정원/);
assert.doesNotMatch(script, /function persistentListElevatorV826\(item\)/);
assert.doesNotMatch(script, /buildListElevatorIconV650\(item\)/);
assert.match(script, /공식자료 승강기 있음/);
assert.doesNotMatch(script, /최대정원|인승/);
assert.match(building, /propertyMatches/);
assert.match(building, /JSBuildingRegisterBadges\.refreshVisible\(\)/);
assert.match(building, /function mergeKnownBadgeV821/);
assert.doesNotMatch(building, /function requestCapacityData/);
assert.match(buildingApi, /const elevators = rows\.reduce/);
assert.match(buildingApi, /road_address=CASE WHEN trim\(COALESCE\(road_address,''\)\)=''/);
assert.match(enrichment, /runScheduledElevatorEnrichment/);
assert.match(enrichment, /getElevatorCapacity/);
assert.match(worker, /query\.action === "elevatorCapacity"[\s\S]*D1_SHEET_CACHE_KEY/);
assert.match(worker, /changeAction: "elevatorCapacity"/);

console.log("elevator capacity v8.2.9 tests passed");
