const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const api = fs.readFileSync(path.join(root, "cloudflare/src/d1-api.js"), "utf8");
const ui = fs.readFileSync(path.join(root, "js/operations-center-v7.js"), "utf8");
const unified = fs.readFileSync(path.join(root, "js/unified-listings-v8.js"), "utf8");
const map = fs.readFileSync(path.join(root, "js/map.js"), "utf8");
const css = fs.readFileSync(path.join(root, "css/operations-center-v7.css"), "utf8");
const unifiedCss = fs.readFileSync(path.join(root, "css/unified-listings-v8.css"), "utf8");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");

assert.match(api, /"transactionCandidates"/);
assert.match(api, /HAVING SUM\(CASE WHEN s\.active=1 THEN 1 ELSE 0 END\)=0/);
assert.match(api, /MAX\(s\.missing_count\)>=3/);
assert.match(api, /lm\.external_url[\s\S]*?image_source\.last_collected_at/);
assert.match(api, /operating_memo[\s\S]*?thumbnail/);
assert.match(api, /LIMIT 2000/);
assert.match(ui, /dashboardCard\("거래확인 후보"[\s\S]*?"transactions"\)/);
assert.match(ui, /window\.openTransactionCandidates = function/);
assert.match(ui, /window\.openTransactionCandidatePropertyV1 = function/);
assert.match(ui, /operations-transaction-detail-v2/);
assert.match(ui, /현재 광고 미노출 · 마지막 정상 사진/);
assert.match(ui, /window\.completeTransactionCandidateV1 = function/);
assert.match(ui, /apiPost\("toggleDone"/);
assert.match(ui, /window\.openTransactionCandidateFromListingV1 = function/);
assert.doesNotMatch(ui, /openTransactionCandidatePropertyV1[\s\S]{0,500}window\.closeOperationsCenter\(\)/);
assert.match(unified, /transaction-check-ribbon-v8135/);
assert.match(unified, /transaction-check-button-v8135/);
assert.match(unified, />계약완료<\/button>/);
assert.match(unified, /광고 미노출 · 확인 필요/);
assert.doesNotMatch(map, /getTransactionCheckClusterClassV8135/);
assert.doesNotMatch(map, /transaction-check-cluster-v8135/);
assert.match(unifiedCss, /#list \.item:has\(\.transaction-check-button-v8135\)/);
assert.doesNotMatch(unifiedCss, /circle-marker\.transaction-check-cluster-v8135/);
assert.match(css, /operations-transaction-detail-v2/);
assert.match(css, /operations-transaction-complete-v2/);
assert.match(html, /operations-center-v7\.js\?v=7\.22\.7-list-transaction-link/);
assert.match(html, /unified-listings-v8\.css\?v=8\.1\.35-transaction-check-emphasis/);
assert.match(html, /map\.js\?v=8\.2\.21-default-cluster-style/);

console.log("transaction candidate list UI tests passed");
